<script>
  import _ from 'lodash'
  import { fromJson, toJsonStr } from './logic/modelParser'
  import { onMounted, onUpdated, reactive, ref } from '@vue/composition-api'
  import GGridGenerator from './GGridGenerator';
  import GDialog from '../GDialog/GDialog'
  import GridModel from './logic/GridModel';

  let gridLayoutInstanceCounter = 0

  export default {
    name: 'GGridLayout',
    components: { GGridGenerator, GDialog },
    props: {
      // layout object generated by grid generator
      layout: [String, Object],
      // boolean value indicate that backgroundColor of grid generator will be applied for grid layout
      displayPreviewColor: Boolean,
      // Allow hide or show grid layout editor
      editable: {
        type: Boolean,
        default: false
      },
      // Allow un-named area render
      passThrough: {
        type: Boolean,
        default: false
      }
    },
    setup(props, context) {
      const layout = fromJson(props.layout)
      // a unique uid for scoped stylesheet of grid layout instance
      const uid = 'gl-' + (gridLayoutInstanceCounter++)
      // vue template ref id
      const refIdWrapperElement = 'el'
      // css generate
      const cssClassPrefix = 'gl-'
      const getAreaClass = name => `${name} ${cssClassPrefix}${name}`
      const addAreaClassForPredefinedArea = () => {
        // assign class for pre-defined area
        const wrapperEl = context.refs[refIdWrapperElement]
        _.each(wrapperEl.querySelectorAll(`[area]`), areaDomNode => {
          const areaName = areaDomNode.getAttribute('area')
          // in case default slot contains multiple element which have the same area value, these areas will be wrapped
          // in a div. The wrapper div will have class value is the value of duplicated area name to get styling of grid generator
          // and we don't want to add class to these area in this case
          if (!areaDomNode.parentNode.classList.contains(areaName)) {
            areaDomNode.classList.add(areaName, `${cssClassPrefix}${areaName}`)
          }

          // now we wipe out all area attribute
          areaDomNode.removeAttribute('area')
        })

        // bring editor out of grid layout
        props.editable && wrapperEl.parentNode.appendChild(context.refs[refIdEditor])
      }

      // editor dialog
      const refIdEditor = 'editor'
      const dialogState = reactive({ show: false })
      function renderEditDialog() {
        return <div ref={refIdEditor}>
          <button vOn:click={() => dialogState.show = true} class="editor-dialog__open-btn">Open Editor</button>
          <g-dialog value={dialogState.show} persistent fullscreen>
            <div class="editor-dialog">
              <div class='editor-dialog__title-bar'>
                <span class='editor-dialog__title-bar__title'>
                  Grid Layout Editor
                </span>
                <button class="close-btn" vOn:click={() => dialogState.show = false}>x</button>
              </div>
              <g-grid-generator layout={toJsonStr(layout)} style="flex: 1"/>
            </div>
          </g-dialog>
        </div>
      }

      // try to find pre-defined VNode in default slot of gridLayout
      function _findVNodesInSlot(name) {
        return _.filter(context.slots.default(), slot => {
          return slot && slot.data && slot.data.attrs && slot.data.attrs['area'] === name
        })
      }

      /**
       * Pass through vnode is a vnode which:
       * - doesn't have "area" attribute
       * - area attribute value which was not defined in layout
       * @private
       */
      function _findPassThroughVNodes() {
        /**
         * Get all name of grid/area model
         * @param model
         * @private
         */
        function _getDeclaredArea(model) {
          let areaNames = [model.name]
          if (model instanceof GridModel) {
            _.each(model.subAreas, area => areaNames.push(..._getDeclaredArea(area)))
          }
          return areaNames
        }

        let declaredNames = _getDeclaredArea(layout)
        return _.filter(context.slots.default(), slot => {
          if (slot == null)
            return false
          else if (!slot.data) {
            return true
          } else if (slot.data && !slot.data.attrs) {
            return true
          } else if (slot.data.attrs['area'] == null || declaredNames.indexOf(slot.data.attrs['area']) === -1) {
            return true
          }
          return false
        })
      }

      function processLayout(model) {
        const cssClassName = getAreaClass(model.name)
        let vNode = _findVNodesInSlot(model.name)
        console.log(model.name, 'found', vNode)
        if (vNode.length > 1) {
          // multiple slot with the same area name
          vNode = <div {...{ attrs: { class: cssClassName } }}>{...vNode}</div>
        } else if (vNode.length === 1) {
          // single slot with area name
          vNode = vNode[0]
          console.log('found single', model.name, vNode[0])
        } else if (!model._parent) {
          // root node -> attach grid-layout attribute id, reference, style, editor dialog, passThrough vNode
          const attrs = { class: cssClassName, [uid]: '' }
          const refWrapper = { ref: refIdWrapperElement }
          const styleVNode = (
              <style type="text/css">
                {model.genCss(uid, { showBackgroundColor: props.displayPreviewColor, prefix: cssClassPrefix })}
              </style>
          )
          const dialogEditVNode = props.editable ? renderEditDialog() : null
          const passThroughVNodes = props.passThrough ? _findPassThroughVNodes() : null

          vNode = <div {...{ attrs }} {...refWrapper}>
            {styleVNode}
            {dialogEditVNode}
            {passThroughVNodes}
            {_.map(model.subAreas, processLayout)}
          </div>
        } else {
          // an area which was declared in layout but not exist in grid template
          // will be rendered as a empty div
          vNode = <div {...{ attrs: { class: cssClassName } }}>
            {_.map(model.subAreas, processLayout)}
          </div>
        }
        return vNode
      }

      onMounted(() => addAreaClassForPredefinedArea())
      onUpdated(() => addAreaClassForPredefinedArea())

      return () => processLayout(layout)
    }
  }
</script>
<style scoped lang="scss">
  .editor-dialog__open-btn {
    position: fixed;
    border: none;
    box-shadow: 0 2px 2px 0 #0003;
    top: 15px;
    right: 10px;
    opacity: 0.6;
    padding: 10px;
    transition: box-shadow 0.5s;

    &:hover {
      opacity: 1;
      cursor: pointer;
      box-shadow: 0 2px 8px 4px #0003;
    }

    &:focus {
      outline: none;
    }
  }

  .editor-dialog {
    display: flex;
    flex-direction: column;
    width: 100%;
    height: 100vh;
    background-color: white;
    border: 1px solid #666;

    &__title-bar {
      display: flex;
      flex-direction: row;
      padding: 10px;
      margin-bottom: 15px;
      background: #eee;
      border-bottom: 1px solid #666;

      &__title {
        flex: 1;
        color: #666;

        & > .uid {
          color: #888;
          font-weight: bold;
        }
      }

      & > .close-btn {
        border-radius: 2px;
        background-color: #888;
        color: #eee;

        &:focus {
          outline: none;
        }

        &:hover {
          cursor: pointer;
          background-color: #aaa;
        }
      }
    }
  }

</style>
