<script>
  import _ from 'lodash'
  import { parseLayoutObject, parseLayoutStr } from './logic/gridLayoutConvert'
  import { generateGridCSS } from './logic/gridCssGenerate'
  import { onMounted, onUpdated, reactive, ref } from '@vue/composition-api'
  import GGridGenerator from './GGridGenerator';
  import GDialog from '../GDialog/GDialog'

  let gridLayoutInstanceCounter = 0

  export default {
    name: 'GGridLayout',
    components: { GGridGenerator, GDialog },
    props: {
      // layout object generated by grid generator
      layout: [String, Object],
      // boolean value indicate that backgroundColor of grid generator will be applied for grid layout
      displayPreviewColor: Boolean,
      // Allow hide or show grid layout editor
      editable: {
        type: Boolean,
        default: true
      },
    },
    setup(props, context) {
      const layout = (typeof(props.layout) === 'string') ? parseLayoutStr(props.layout) : parseLayoutObject(props.layout)

      // vue template ref id
      const refIdWrapperElement = 'el'

      // a unique uid for scoped stylesheet of grid layout instance
      const uid = 'data-g-grid-layout-' + (gridLayoutInstanceCounter++)

      const addAreaClassForPredefinedArea = () => {
        // assign class for pre-defined area
        const wrapperEl = context.refs[refIdWrapperElement]
        const areaNodes = wrapperEl.querySelectorAll(`[area]`)
        _.each(areaNodes, node => node.classList.add(node.getAttribute('area')))

        // bring editor out of grid layout
        props.editable && wrapperEl.parentNode.appendChild(context.refs[refIdEditor])
      }

      // editor dialog
      const refIdEditor = 'editor'
      const dialogState = reactive({ show: false })
      function renderEditDialog() {
        return <div ref={refIdEditor}>
          <button vOn:click={() => dialogState.show = true} class="editor-dialog__open-btn">Open Editor</button>
          <g-dialog value={dialogState.show} persistent fullscreen>
            <div class="editor-dialog">
              <div class='editor-dialog__title-bar'>
                <span class='editor-dialog__title-bar__title'>
                  Grid Layout Editor
                </span>
                <button class="close-btn" vOn:click={() => dialogState.show = false}>x</button>
              </div>
              <g-grid-generator layout={layout} style="flex: 1"/>
            </div>
          </g-dialog>
        </div>
      }

      onMounted(() => addAreaClassForPredefinedArea())
      onUpdated(() => addAreaClassForPredefinedArea())

      // try to find pre-defined VNode in default slot of gridLayout
      function _findVnodeInSlot(name) {
        return _.find(context.slots.default(), slot => {
          return slot && slot.data && slot.data.attrs && slot.data.attrs['area'] === name
        })
      }

      function processLayout(model) {
        // find a pre-defined Vnode in default slot, if default slot doesn't include current name
        // then add new div wrapper
        let vNode = _findVnodeInSlot(model.name)
        if (!vNode) {
          // assign model class to vnode
          const attrs = { class: model.name }
          let refWrapper = null
          let styleEl = null
          let dialogEdit = null
          // assign stuff if model is root node
          if (!model.parent) {
            attrs[uid] = ''
            refWrapper = { ref : refIdWrapperElement }
            styleEl = <style type="text/css">
              {generateGridCSS(layout, uid, { showBackgroundColor: props.displayPreviewColor })}
            </style>
            dialogEdit = props.editable ? renderEditDialog() : null
          }
          vNode = <div {...{ attrs }} {...refWrapper}>
            {styleEl}
            {dialogEdit}
            {_.map(model.subAreas, processLayout)}
          </div>
        }

        return vNode
      }

      return function() {
        return processLayout(layout)
      }
    }
  }
</script>
<style scoped lang="scss">
  .editor-dialog__open-btn {
    position: fixed;
    border: none;
    box-shadow: 0 2px 2px 0 #0003;
    top: 15px;
    right: 10px;
    opacity: 0.6;
    padding: 10px;
    transition: box-shadow 0.5s;

    &:hover {
      opacity: 1;
      cursor: pointer;
      box-shadow: 0 2px 8px 4px #0003;
    }
    &:focus {
      outline: none;
    }
  }

  .editor-dialog {
    display: flex;
    flex-direction: column;
    width: 100%;
    height: 100vh;
    background-color: white;
    border: 1px solid #666;

    &__title-bar {
      display: flex;
      flex-direction: row;
      padding: 10px;
      margin-bottom: 15px;
      background: #eee;
      border-bottom: 1px solid #666;

      &__title {
        flex: 1;
        color: #666;

        &>.uid {
          color: #888;
          font-weight: bold;
        }
      }

      &>.close-btn {
        border-radius: 2px;
        background-color: #888;
        color: #eee;

        &:focus {
          outline: none;
        }

        &:hover {
          cursor: pointer;
          background-color: #aaa;
        }
      }
    }
  }

</style>
