<script>
  import { computed } from '@vue/composition-api';
  import GTreeFactory, { genTextFactory } from './GTreeFactory';
  import GIcon from '../GIcon/GIcon';

  export function getPropsNameAZPrimitiveFirst(obj) {
    // the higher the index, the higher priority
    const typePriority = ['function', 'object', 'array', 'string', 'number', 'boolean']

    let objKeys = Object.keys(obj)
    let objKeysValueType = {}

    objKeys.forEach(key => objKeysValueType[key] = typeof obj[key])

    const sortResult = objKeys.sort((key1, key2) => {
      let typePriority1 = typePriority.indexOf(objKeysValueType[key1])
      let typePriority2 = typePriority.indexOf(objKeysValueType[key2])
      // the same type, compare key name
      if (typePriority1 === typePriority2) {
        return key1 > key2 ? 1 : -1
      } else // different type, order by type
      {
        return typePriority2 - typePriority1
      }
    })

    return sortResult
  }

  export default {
    name: 'GTreeViewJson',
    components: { GIcon },
    props: {
      expandLevel: {
        type: Number,
        default: 100
      },
      maxItemTextLength: {
        type: Number,
        default: 2000
      },
      data: [Object, Array],
    },
    setup(props, context) {
      function getValueClass(text) {
        switch (text.valueType) {
          case 'array':
            return 'g-tree-view__item-value-array'
          case 'string':
            return 'g-tree-view__item-value-string'
          default:
            return 'g-tree-view__item-value-' + typeof (text.value)
        }
      }

      function formatTextValue(text) {
        switch (text.valueType) {
          case 'string':
            return `"${text.value}"`
          case 'array' :
            return `Array (${text.value.length})`
          case 'boolean':
            return text.value ? 'true' : 'false'
          default:
            return text.value
        }
      }

      function genValueNode(text) {
        if (text.valueType === 'skip') return null
        if (text.valueType === 'object') {
          return [
            <span class='g-tree-view__item-value-object'>Object &#123; </span>,
            text.value.outputValues.map(outputValue => [
                  <span class="g-tree-view__item-var-name">{outputValue.varName}</span>,
                  <span class='g-tree-view__item-separate-symbol'>: </span>,
                  genValueNode(outputValue),
                  <span class='g-tree-view__item-separate-symbol'>, </span>
                ]
            ),
            text.value.moreSymbol ? <span class='g-tree-view__item-separate-symbol'>...</span> : undefined,
            <span class='g-tree-view__item-value-object'> &#125;</span>
          ]
        } else {
          return <span class={getValueClass(text)}>{formatTextValue(text)}</span>
        }
      }

      const genNode = function (node, text /*result generated by itemText function*/, childrenVNodes, isLast, state, path) {
        return <li>
          {
            childrenVNodes
                ? <span class='g-tree-view__collapse-expand' vOn:click={() => state.collapse = !state.collapse}>
                  <span>
                    {state.collapse ? <g-icon small color="red">chevron_right</g-icon> : <g-icon small color="red">expand_more</g-icon>}
                  </span>
                </span>
                : <span class='g-tree-view__primitive-item'></span>
          }

          <span class='g-tree-view__item-icon-wrapper'>
            {
              text.valueType === 'object'
                  ? <g-icon small color="orange">reorder</g-icon>
                  : text.valueType === 'array'
                  ? <g-icon small color="blue">list</g-icon>
                  : <g-icon small color="blue">local_atm</g-icon>
            }
          </span>


          {text.varName ? [<span class="g-tree-view__item-var-name">{text.varName}</span>,
            <span class='g-tree-view__item-separate-symbol'> = </span>] : undefined}

          {genValueNode(text)}

          {!state.collapse ? childrenVNodes : null}
        </li>
      }
      const genWrapper = function (childrenVNodes) {
        return <ul>{childrenVNodes}</ul>
      }
      const genRootWrapper = function (childrenVNodes) {
        return (
            <div root>
              <ul>{childrenVNodes}</ul>
            </div>
        )
      }


      // TODO: Move to helper
      function createValueDesc(name, value, type) {
        return { varName: name, value: value, valueType: type }
      }

      function jsonStringlifyReplacer(object) {
        const outputValues = []
        let moreSymbol = false

        const allKeyOrdered = getPropsNameAZPrimitiveFirst(object)
        for (let index = 0; index < allKeyOrdered.length; index++) {
          let key = allKeyOrdered[index]
          let val = object[key]
          let typeOfVal = typeof val

          // only add primitive value
          // skip if value is object, array
          let valDesc
          if (typeOfVal !== 'object') {
            // cut the string if it's length too long
            if (typeOfVal === 'string' && val.length > 50) {
              valDesc = createValueDesc(key, val.substr(0, 20) + '...' + val.substr(val.length - 1 - 20), typeOfVal)
            } else {
              valDesc = createValueDesc(key, val, typeOfVal)
            }
          } else {
            valDesc = createValueDesc(key, null, 'skip')
          }

          outputValues.push(valDesc)

          if (index === 5) {
            moreSymbol = true
            break;
          }
        }

        return {
          outputValues,
          moreSymbol
        }
      }

      const itemText = (node, isRoot) => {
        if (isRoot) {
          return { varName: 'result', valueType: 'object', value: jsonStringlifyReplacer(node) }
        } else {
          if (typeof node === 'object') {
            const firstPropName = Object.keys(node)[0];
            const firstPropValue = node[firstPropName];
            if (Array.isArray(firstPropValue)) {
              return { varName: firstPropName, valueType: 'array', value: firstPropValue }
            } else if (typeof firstPropValue === 'object') {
              return { varName: firstPropName, valueType: 'object', value: jsonStringlifyReplacer(firstPropValue) }
            } else {
              return { varName: firstPropName, value: firstPropValue, valueType: typeof firstPropValue }
            }
          } else {
            return { value: node, valueType: typeof node }
          }
        }
      }
      const itemChildren = (node, isRoot) => {
        if (Array.isArray(node)) {
          return node
        } else if (typeof node === 'object') {
          const converter = node => Object.keys(node).map(k => ({ [k]: node[k] }))
          const firstPropValue = node[Object.keys(node)[0]];

          if (isRoot) {
            return converter(node)
          } else if (Array.isArray(firstPropValue)) {
            return firstPropValue;
          } else if (typeof firstPropValue === 'object') {
            return converter(firstPropValue);
          } else {
            return firstPropValue;
          }
        } else {
          // primitive
          return node;
        }
      }

      const cptExpandLevel = computed(() => props.expandLevel)
      const { treeStates, genTree } = GTreeFactory({
        genNode,
        genWrapper,
        genRootWrapper,
        data: props.data,
        itemText,
        itemChildren,
        cptExpandLevel
      })
      return { treeStates, genTree }
    },
    render() {
      return this.genTree();
    }
  }


</script>
<style scoped lang="scss">
  ul {
    list-style-type: none;
    padding-left: 20px;

    background-color: rgb(46, 48, 50);
  }

  .g-tree-view {
    &__item {
      &-icon-wrapper {
        display: inline-block;
        width: 20px;
        height: 100%;
        vertical-align: middle;
      }

      &-text-expand {
        color: blue;
        cursor: pointer;
      }

      &-var-name {
        color: rgb(246, 123, 121);
      }

      &-separate-symbol {
        color: rgb(168, 168, 168);
      }

      &-value {
        &-string {
          color: rgb(185, 125, 82);
        }

        &-boolean {
          color: rgb(69, 133, 206);
        }

        &-number {
          color: rgb(233, 254, 122);
        }

        &-array {
          color: rgb(168, 168, 168);
        }

        &-object {
          color: rgb(109, 109, 109);
        }
      }
    }

    &__primitive-item {
      display: inline-block;
      width: 15px;
    }

    &__collapse-expand {
      display: inline-block;
      width: 15px;
      alignment: center;
      cursor: pointer;

      span {
        width: 5px;
        height: 5px;
      }
    }
  }

</style>
