<script>
  import { computed } from '@vue/composition-api';
  import GTreeFactory, { genTextFactory } from './GTreeFactory';
  import GIcon from '../GIcon/GIcon';

  export function getPropsNameAZPrimitiveFirst(obj) {
    // the higher the index, the higher priority
    const typePriority = ['function', 'object', 'array', 'string', 'number', 'boolean']

    let objKeys = Object.keys(obj)
    let objKeysValueType = {}

    objKeys.forEach(key => objKeysValueType[key] = typeof obj[key])

    const sortResult = objKeys.sort((key1, key2) => {
      let typePriority1 = typePriority.indexOf(objKeysValueType[key1])
      let typePriority2 = typePriority.indexOf(objKeysValueType[key2])
      // the same type, compare key name
      if (typePriority1 === typePriority2)
        return key1 > key2 ? 1: -1
      else // different type, order by type
        return typePriority2 - typePriority1
    })

    return sortResult
  }

  export default {
    name: 'GTreeViewJson',
    components: { GIcon },
    props: {
      expandLevel: {
        type: Number,
        default: 100
      },
      maxItemTextLength: {
        type: Number,
        default: 2000
      },
      data: [Object, Array],
    },
    setup(props, context) {
      // TODO: Move to render()
      const genNode = function (node, text /*result generated by itemText function*/, childrenVNodes, isLast, state, path) {
        return <li>
          {
            childrenVNodes
              ? <span class='g-tree-view__collapse-expand' vOn:click={() => state.collapse = !state.collapse}>
                  <span>
                    {state.collapse ? <g-icon small color="red">chevron_right</g-icon> : <g-icon small color="red">expand_more</g-icon>}
                  </span>
                </span>
              : <span class='g-tree-view__primitive-item'></span>
          }

          <span class='g-tree-view__item-icon-wrapper'>
            {
              text.indexOf('Object') > -1
                  ? <g-icon small color="orange">reorder</g-icon>
                  : text.indexOf('Array') > -1
                    ? <g-icon small color="blue">list</g-icon>
                    : <g-icon small color="blue">local_atm</g-icon>
            }
          </span>


          {
            text.length > props.maxItemTextLength
              ? [text.substr(0, props.maxItemTextLength),
                <span class='g-tree-view__item-text-expand' vOn:click={() => state.collapse = !state.collapse}>
                  ...
                </span>]
              : text
          }

          {!state.collapse ? childrenVNodes : null}
        </li>
      }
      const genWrapper = function (childrenVNodes) {
        return <ul>{childrenVNodes}</ul>
      }
      const genRootWrapper = function (childrenVNodes) {
        return (
            <div root>
              <ul>{childrenVNodes}</ul>
            </div>
        )
      }


      // TODO: Move to helper
      function jsonStringlifyReplacer(__, value) {
        let output = ''
        let keys = getPropsNameAZPrimitiveFirst(value)
        for (let index=0; index < keys.length; index++) {
          let key = keys[index]
          let val = value[key]
          output += `, ${key}: `
          if (typeof val !== 'object') {
            if (typeof val === 'string') {
              if (val.length > 50) {
                output += val.substr(0, 25) + '...' + val.substr(val.length - 1 - 25)
              } else {
                output += val
              }
            } else {
              output += val
            }
          }
          if (index === 5) {
            output += ', ...'
            break;
          }
        }

        return `{ ${output.substr(1)} }`
      }

      // TODO: Move to helper
      function removeQuote(str) {
        // output of replacer automatically add "" surround output value
        // that why we need to remove it substr(1, str.length - 2)
        return str.substr(1, str.length - 2).replace(/\"([^(\")"]+)\":/g, "$1:")
      }

      const cptExpandLevel = computed(() => props.expandLevel)
      const itemText = (node, isRoot) => {
        if (isRoot) {
          return `result = Object ${removeQuote(JSON.stringify(node, jsonStringlifyReplacer, 1))}`
        } else
          {
          if (typeof node === 'object') {
            const firstPropName = Object.keys(node)[0];
            const firstPropValue = node[firstPropName];
            if (Array.isArray(firstPropValue)) {
              return `${firstPropName} = Array(${firstPropValue.length})`
            } else if (typeof firstPropValue === 'object') {
              return `${firstPropName} = Object ${ removeQuote(JSON.stringify(firstPropValue, jsonStringlifyReplacer, 1)) }`
            } else {
              return `${Object.keys(node)[0]} = ${firstPropValue}`
            }
          } else {
            return `${node}`
          }
        }
      }

      const itemChildren = (node, isRoot) => {
        if (Array.isArray(node)) {
          return node
        } else if (typeof node === 'object') {
          const converter = node => Object.keys(node).map(k => ({ [k]: node[k] }))
          const firstPropValue = node[Object.keys(node)[0]];

          if (isRoot) {
            return converter(node)
          } else if (Array.isArray(firstPropValue)) {
            return firstPropValue;
          } else if (typeof firstPropValue === 'object') {
            return converter(firstPropValue);
          } else {
            return firstPropValue;
          }
        } else {
          // primitive
          return node;
        }
      }

      const { treeStates, genTree } = GTreeFactory({
        genNode,
        genWrapper,
        genRootWrapper,
        data: props.data,
        itemText,
        itemChildren,
        cptExpandLevel
      })

      return { treeStates, genTree }
    },
    render() {
      return this.genTree();
    }
  }


</script>
<style scoped lang="scss">
  ul {
    list-style-type: none;
    padding-left: 20px;
    border-left: 1px dashed #aaa;
  }

  .g-tree-view {
    &__item-icon-wrapper {
      display: inline-block;
      width: 20px;
      height: 100%;
      vertical-align: middle;
    }

    &__item-text-expand {
      color: blue;
      cursor: pointer;
    }

    &__primitive-item {
      display: inline-block;
      width: 15px;
    }

    &__collapse-expand {
      display: inline-block;
      width: 15px;
      alignment: center;
      cursor: pointer;

      span {
        width: 5px;
        height: 5px;
      }
    }
  }

</style>
